### ISSUE TITLE
EPIC: GUI Development

### ISSUE THREAD

**Issue by tangkong** [pcdshub/superscore#19]
This is an EPIC tracking development of the `superscore` GUI.  The plan is for this gui to be built with pyQT, with assistance from pyDM widgets where sensible.  It is likely necessary to build many of our own widgets and views.  

Tentative task list (Convert to issues when work begins):
- [ ] Build Model(QAbstractItemModel), compatible with tree and list views
- [ ] Build TreeView (context menu, icons, etc)
- [ ] Build Base widget (possibly pcdsutils.qt.DesignerDisplay)
- [ ] Build search-filter page / tab / box (integrating with tree view and switching to relevant page)
- [ ] Build Entry comparison page
- [ ] Build Collection builder page
- [ ] Build Entry views (Collection, Parameter)
- [ ] Build apply-to-EPICS page
- [ ] Build authentication menus and flow

**Comment by tangkong** [comment]
Basis of GUI development started in #38
