### ISSUE TITLE
EPIC: Beta GUI Development

### ISSUE THREAD

**Issue by tangkong** [pcdshub/superscore#20]
GUI related tasks targeting the slightly more complete beta release.

Tasks, to be converted to issues when work begins:
- [ ] Build authentication menus and flow
- [ ] Build tagging menus and user flows
- [ ] Build database selection menu
