### ISSUE TITLE
EPIC: Archiver integration

### ISSUE THREAD

**Issue by shilorigins** [pcdshub/superscore#39]
The Archiver Appliance can be used as a source of historical PV data, both to fill gaps in live data during a save and to create snapshots for past timestamps.

# Task List
- [ ] Configure connection to Archiver
- [ ] Enable creating a snapshot from Archiver data
- [ ] Enable comparing an existing snapshot to data from a timestamp
- [ ] Implement Archiver fallback for missing live data
